import acers5 from './Image/acers5.jpeg'
import applem2 from './Image/applem2.jpeg'
import dellxps from './Image/dellxps.jpeg'
import hps14 from './Image/hps14.jpeg'
import lenevox1 from './Image/lenevox1.jpeg'
import lggram17 from './Image/lggram17.jpeg'
import microsofts5 from './Image/microsofts5.jpeg'
import msip14 from './Image/msip14.jpeg'
import razerb15 from './Image/razerb15.jpeg'
import rogg14 from './Image/rogg14.jpeg'



export const laptops = [
  {
    id: 1,
    title: "Dell XPS 13",
    specs: [
      "Intel Core i7-1360P (13th Gen, 12-core, 16-thread)",
      "Base Clock: 2.2GHz, Turbo Boost up to 5.0GHz",
      "Intel Iris Xe Graphics",
      "16GB LPDDR5 RAM @ 5200MHz (soldered)",
      "512GB PCIe Gen 4 NVMe SSD",
      "13.4” FHD+ (1920 x 1200) InfinityEdge Display",
      "500 nits brightness",
      "100% sRGB color gamut",
      "16:10 aspect ratio",
      "Anti-reflective, Anti-smudge coating",
      "Windows 11 Home, 64-bit",
      "2 x Thunderbolt 4 (USB-C) with Power Delivery",
      "No headphone jack (USB-C to 3.5mm adapter included)",
      "Wi-Fi 6E (Killer AX1650)",
      "Bluetooth 5.3",
      "Fingerprint Reader (Power Button)",
      "Backlit Edge-to-Edge Keyboard",
      "Precision Glass Touchpad",
      "Dual speakers with Waves MaxxAudio Pro",
      "Dual-array mics for voice assistant",
      "720p IR Camera with Windows Hello support",
      "ExpressCharge: Up to 80% in 60 minutes",
      "52Wh Lithium-ion Battery (Integrated)",
      "Aluminum CNC chassis, Arctic White finish",
      "Fanless cooling design",
      "Weight: 1.17 kg (2.58 lbs)"
    ],
    price: 1299,
    image: dellxps
  },
  {
    id: 2,
    title: "Apple MacBook Air M2",
    specs: [
      "Apple M2 chip (8-core CPU, 8-core GPU)",
      "16-core Neural Engine",
      "8GB Unified Memory",
      "256GB SSD Storage (NVMe)",
      "13.6” Liquid Retina Display (2560 x 1664)",
      "500 nits brightness",
      "P3 Wide Color, True Tone",
      "macOS Sonoma",
      "Magic Keyboard with Touch ID",
      "Fanless (silent) cooling",
      "2 x Thunderbolt / USB 4 ports",
      "MagSafe 3 Charging Port",
      "Wi-Fi 6 (802.11ax)",
      "Bluetooth 5.3",
      "1080p FaceTime HD Camera",
      "Three-mic array with directional beamforming",
      "Four-speaker sound system with Spatial Audio",
      "Battery: Up to 18 hours",
      "30W USB-C Power Adapter",
      "Weight: 1.24 kg (2.73 lbs)",
      "Recycled aluminum enclosure"
    ],
    price: 1099,
    image: applem2
  },
  {
    id: 3,
    title: "HP Spectre x360",
    specs: [
      "Intel Core i7-1355U (13th Gen, 10-core)",
      "Base Frequency: 1.7GHz, Max Turbo: 5.0GHz",
      "Intel Iris Xe Graphics",
      "16GB LPDDR4x RAM @ 4266MHz",
      "1TB PCIe Gen 4 NVMe SSD",
      "13.5” 3K2K OLED Touchscreen (3000 x 2000)",
      "OLED, 400 nits, HDR",
      "360° Convertible Hinge",
      "Windows 11 Home",
      "Wi-Fi 6E + Bluetooth 5.3",
      "Fingerprint Reader + IR Webcam",
      "Bang & Olufsen Quad Speakers",
      "Backlit Keyboard",
      "HP Rechargeable Tilt Pen included",
      "1 x Thunderbolt 4, 2 x USB-C, 1 x USB-A",
      "Battery life: Up to 15 hours",
      "Fast Charge: 50% in 45 minutes",
      "Aluminum chassis",
      "Weight: 1.3 kg",
      "Color: Nightfall Black"
    ],
    price: 1399,
    image: hps14
  },
  {
    id: 4,
    title: "Lenovo ThinkPad X1 Carbon Gen 11",
    specs: [
      "Intel Core i7-1370P vPro (13th Gen)",
      "12 Cores (4P + 8E), 16 Threads",
      "Intel Iris Xe Graphics",
      "16GB LPDDR5 6400MHz RAM (soldered)",
      "512GB PCIe Gen 4 SSD",
      "14” WUXGA IPS Anti-Glare (1920 x 1200)",
      "400 nits brightness",
      "100% sRGB Color Accuracy",
      "Windows 11 Pro",
      "Wi-Fi 6E, Bluetooth 5.2",
      "2 x Thunderbolt 4, 2 x USB-A, HDMI 2.0b",
      "Fingerprint Reader (Power Button)",
      "720p + IR Webcam with Privacy Shutter",
      "Dolby Vision Support",
      "Dolby Atmos Speaker System",
      "Backlit Keyboard (spill-resistant)",
      "RapidCharge: 80% in 1 hour",
      "57Wh Battery",
      "MIL-STD-810H Certified (Military-grade)",
      "Weight: 1.13 kg",
      "Color: Deep Black"
    ],
    price: 1499,
    image: lenevox1
  },
  {
    id: 5,
    title: "ASUS ROG Zephyrus G14",
    specs: [
      "AMD Ryzen 9 7940HS (8-core/16-thread)",
      "Base Clock: 3.2GHz, Boost up to 5.2GHz",
      "NVIDIA GeForce RTX 4060 8GB GDDR6",
      "32GB DDR5 4800MHz RAM (upgradeable)",
      "1TB PCIe 4.0 NVMe SSD",
      "14” QHD+ (2560 x 1600) 165Hz Display",
      "500 nits brightness, 100% DCI-P3",
      "Windows 11 Home",
      "AniMe Matrix LED Lid",
      "Wi-Fi 6E, Bluetooth 5.2",
      "ROG Intelligent Cooling System",
      "Dolby Atmos 4-speaker setup",
      "Backlit RGB Keyboard",
      "1 x HDMI 2.1, 2 x USB-C, 2 x USB-A",
      "1 x 3.5mm Combo Jack",
      "Webcam: FHD with IR (Windows Hello)",
      "76Wh Battery",
      "USB-C Power Delivery",
      "Weight: 1.65 kg",
      "Color: Eclipse Gray"
    ],
    price: 1699,
    image: rogg14
  },
  {
    id: 6,
    title: "Acer Swift 5",
    specs: [
      "Intel Core i5-1335U (13th Gen, 10-core)",
      "Intel Iris Xe Graphics",
      "16GB LPDDR5 RAM",
      "512GB PCIe Gen 4 SSD",
      "14” FHD IPS Display (1920 x 1080)",
      "100% sRGB Color Gamut",
      "Windows 11 Home",
      "Magnesium-Aluminum Alloy Build",
      "Wi-Fi 6E, Bluetooth 5.2",
      "2 x Thunderbolt 4, HDMI 2.1, USB-A",
      "Backlit Keyboard",
      "Fingerprint Reader (Power Button)",
      "720p HD Webcam",
      "Stereo Speakers with DTS Audio",
      "Battery: 56Wh, Up to 14 hours",
      "Fast Charge: 4 hours use in 30 mins",
      "Precision Touchpad",
      "Fan cooling",
      "Weight: 1.2 kg",
      "Color: Mist Green"
    ],
    price: 899,
    image: acers5
  },
  {
    id: 7,
    title: "Microsoft Surface Laptop 5",
    specs: [
      "Intel Core i5-1235U (12th Gen, 10-core)",
      "Intel Iris Xe Graphics",
      "8GB LPDDR5 RAM",
      "512GB SSD Storage",
      "13.5” PixelSense Touch Display (2256 x 1504)",
      "3:2 Aspect Ratio, 400 nits",
      "Dolby Vision, Gorilla Glass 5",
      "Windows 11 Home",
      "Alcantara Keyboard Palm Rest",
      "Backlit Keyboard",
      "Wi-Fi 6, Bluetooth 5.1",
      "Thunderbolt 4, USB-A, Surface Connect",
      "Omnisonic Speakers with Dolby Atmos",
      "HD Webcam with Windows Hello",
      "Fast Charging: 80% in under 60 minutes",
      "Battery life: Up to 18 hours",
      "52.4Wh Battery",
      "Precision Touchpad",
      "Weight: 1.29 kg",
      "Color: Sage Green"
    ],
    price: 1199,
    image: microsofts5
  },
  {
    id: 8,
    title: "Razer Blade 15",
    specs: [
      "Intel Core i9-13980HX (13th Gen, 24-core)",
      "Base Clock: 2.2GHz, Turbo: 5.6GHz",
      "NVIDIA GeForce RTX 4070 (8GB GDDR6)",
      "32GB DDR5 RAM (upgradeable)",
      "1TB PCIe Gen 4 SSD (upgradeable)",
      "15.6” QHD 240Hz (2560 x 1440) Display",
      "100% DCI-P3 Color, G-Sync Ready",
      "Windows 11 Home",
      "Per-Key RGB Chroma Keyboard",
      "Vapor Chamber Cooling System",
      "Wi-Fi 6E, Bluetooth 5.3",
      "THX Spatial Audio Speakers",
      "1080p IR Webcam with Windows Hello",
      "Thunderbolt 4, HDMI 2.1, SD Card Reader",
      "RGB Underglow Lighting",
      "Aluminum CNC Unibody Design",
      "Battery: 80Wh",
      "Compact 230W GaN Power Adapter",
      "Weight: 2.01 kg",
      "Color: Black"
    ],
    price: 2399,
    image: razerb15
  },
  {
    id: 9,
    title: "LG Gram 17",
    specs: [
      "Intel Core i7-1360P (13th Gen)",
      "Intel Iris Xe Graphics",
      "16GB LPDDR5 RAM",
      "1TB PCIe 4.0 NVMe SSD",
      "17” WQXGA (2560 x 1600) IPS Display",
      "Anti-Glare, 99% DCI-P3",
      "Windows 11 Home",
      "Ultra-Lightweight: 1.35kg",
      "MIL-STD 810G Certified",
      "2 x Thunderbolt 4, 2 x USB-A, HDMI, microSD",
      "Backlit Keyboard",
      "Fingerprint Reader (Power Key)",
      "FHD Webcam with IR",
      "DTS:X Ultra Audio",
      "Battery: 80Wh, Up to 20.5 hrs",
      "Wi-Fi 6E, Bluetooth 5.2",
      "Dual cooling fans",
      "Aluminum alloy body",
      "Color: Obsidian Black",
      "Ergonomic hinge design"
    ],
    price: 1599,
    image: lggram17
  },
  {
    id: 10,
    title: "MSI Prestige 14",
    specs: [
      "Intel Core i7-1280P (12th Gen, 14-core)",
      "NVIDIA GeForce GTX 1650 4GB GDDR6",
      "16GB LPDDR4x RAM",
      "512GB PCIe NVMe SSD",
      "14” FHD (1920 x 1080) Anti-Glare Display",
      "Windows 11 Pro",
      "Backlit Keyboard",
      "Fingerprint Reader + Windows Hello",
      "2 x Thunderbolt 4, HDMI, USB-A",
      "Hi-Res Audio Certified",
      "Dual-fan cooling system",
      "Wi-Fi 6, Bluetooth 5.1",
      "HD Webcam with Noise Reduction",
      "Aluminum Chassis",
      "Battery: 52Wh, Fast Charging",
      "Weight: 1.3 kg",
      "Color: Pure White",
      "Military-grade durability (MIL-STD-810G)",
      "Pre-installed Creator Center Software",
      "180° lay-flat hinge"
    ],
    price: 1149,
    image: msip14
  }
];

